#ifndef GUARD_EXODUS_FEATURES_H
#define GUARD_EXODUS_FEATURES_H

enum ExodusGameMode {
    EXODUSGAMEMODE_Classic,
    EXODUSGAMEMODE_Enhanced,
};

enum ExodusFeature {
    EF_MULTISIZE_PLANETS,
    EF_MULTISIZE_PLANETS_COLONISE,
    EF_MULTISIZE_PLANETS_PANEL,
    EF_WRECKAGE_COVER,
    EF_ALLIANCE_LIMIT,
    EF_FESTIVAL_LIMIT,
    EF_FESTIVAL_REQUIRES_CITY,
    EF_COUNSELLOR_EXTRA,
    EF_UNPAID_OFFICER_NAMED,
    EF_OFFICER_COST_INFO,
    EF_FLIP_BUTTONS,
    EF_CPU_EXPLOITS_VOLCANO,
    EF_HUMAN_NO_RANDOM_ALLY_LOSS,
    EF_AIM_MONEY_EXCLUDE_ARMY,
    //EF_PLANET_ITERATION_RANDOMISE,
    EF_REBEL_REPUBLIC_CHANCE,
    EF_PREVENT_AI_BATTLE_BACKTRACK,
    EF_BOMBING_LIMIT_HUMAN,
    EF_PLANET_RECALLABLE_SUMMARIES,
    EF_GALAXY_MAP_PLANET_MARKERS,
    EF_OPTIMISE_ARMY_PRODUCTION_PRIORITIES,
    EF_FAST_FADES,
    EF_LUNAR_BATTLE_ADVANCED_HP_INFO,
    EF_LUNAR_BATTLE_INF_DISCOVER_MINES,
    EF_LUNAR_BATTLE_PROMOTION,
    EF_REFINED_SCIENCE_REPORTS,
    EF_SMARTER_STATUS_LIGHTS,
    EF_ADVANCED_GALAXY_MAP,
    EF_SPACE_BATTLE_MC,
    EF_FIX_AI_TERROR,
    EF_FIX_FLEET_ADMIRAL,
    EF_DISABLE_MULTIPLAYER,
};

void exodus_set_game_mode(ExodusGameMode);
bool ENHANCED();
bool FEATURE(ExodusFeature);

#endif
